# Generated by Django 4.1.3 on 2022-11-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_title',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='genre_title',
            field=models.CharField(default='Playlist Wub Dub', max_length=40),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untiltled', max_length=300)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plays', models.PositiveIntegerField(null=True)),
                ('explicit', models.BooleanField()),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
            ],
        ),
    ]
