# Generated by Django 4.1.3 on 2022-11-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artist_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='genre_title',
            new_name='playlist_title',
        ),
    ]
