# Generated by Django 4.1.3 on 2022-11-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_genre_title_playlist_playlist_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='album_title',
            new_name='artist_title',
        ),
    ]
