# Generated by Django 4.1.3 on 2022-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_rename_album_title_artist_artist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(default='Single', max_length=40),
        ),
    ]
