# Generated by Django 4.1.3 on 2022-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_album_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='album_songs', to='music.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='related_songs', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='playlist_songs', to='music.playlist'),
        ),
    ]
